./CordicFunctionGen  6 > ../src/fixed_cordic/cordic-6b.hpp  > ../src/fixed_cordic/cordic-6b.hpp
./CordicFunctionGen  7 > ../src/fixed_cordic/cordic-7b.hpp  > ../src/fixed_cordic/cordic-7b.hpp
./CordicFunctionGen  8 > ../src/fixed_cordic/cordic-8b.hpp  > ../src/fixed_cordic/cordic-8b.hpp
./CordicFunctionGen  9 > ../src/fixed_cordic/cordic-9b.hpp  > ../src/fixed_cordic/cordic-9b.hpp
./CordicFunctionGen 10 > ../src/fixed_cordic/cordic-10b.hpp > ../src/fixed_cordic/cordic-10b.hpp
./CordicFunctionGen 11 > ../src/fixed_cordic/cordic-11b.hpp > ../src/fixed_cordic/cordic-11b.hpp
./CordicFunctionGen 12 > ../src/fixed_cordic/cordic-12b.hpp > ../src/fixed_cordic/cordic-12b.hpp
./CordicFunctionGen 13 > ../src/fixed_cordic/cordic-13b.hpp > ../src/fixed_cordic/cordic-13b.hpp
./CordicFunctionGen 14 > ../src/fixed_cordic/cordic-14b.hpp > ../src/fixed_cordic/cordic-14b.hpp
./CordicFunctionGen 15 > ../src/fixed_cordic/cordic-15b.hpp > ../src/fixed_cordic/cordic-15b.hpp
./CordicFunctionGen 16 > ../src/fixed_cordic/cordic-16b.hpp > ../src/fixed_cordic/cordic-16b.hpp
./CordicFunctionGen 17 > ../src/fixed_cordic/cordic-17b.hpp > ../src/fixed_cordic/cordic-17b.hpp
./CordicFunctionGen 18 > ../src/fixed_cordic/cordic-18b.hpp > ../src/fixed_cordic/cordic-18b.hpp
./CordicFunctionGen 19 > ../src/fixed_cordic/cordic-19b.hpp > ../src/fixed_cordic/cordic-19b.hpp
./CordicFunctionGen 20 > ../src/fixed_cordic/cordic-20b.hpp > ../src/fixed_cordic/cordic-20b.hpp
./CordicFunctionGen 21 > ../src/fixed_cordic/cordic-21b.hpp > ../src/fixed_cordic/cordic-21b.hpp
./CordicFunctionGen 22 > ../src/fixed_cordic/cordic-22b.hpp > ../src/fixed_cordic/cordic-22b.hpp
./CordicFunctionGen 23 > ../src/fixed_cordic/cordic-23b.hpp > ../src/fixed_cordic/cordic-23b.hpp
./CordicFunctionGen 24 > ../src/fixed_cordic/cordic-24b.hpp > ../src/fixed_cordic/cordic-24b.hpp
./CordicFunctionGen 25 > ../src/fixed_cordic/cordic-25b.hpp > ../src/fixed_cordic/cordic-25b.hpp
./CordicFunctionGen 26 > ../src/fixed_cordic/cordic-26b.hpp > ../src/fixed_cordic/cordic-26b.hpp
./CordicFunctionGen 27 > ../src/fixed_cordic/cordic-27b.hpp > ../src/fixed_cordic/cordic-27b.hpp
./CordicFunctionGen 28 > ../src/fixed_cordic/cordic-28b.hpp > ../src/fixed_cordic/cordic-28b.hpp
./CordicFunctionGen 29 > ../src/fixed_cordic/cordic-29b.hpp > ../src/fixed_cordic/cordic-29b.hpp
./CordicFunctionGen 30 > ../src/fixed_cordic/cordic-30b.hpp > ../src/fixed_cordic/cordic-30b.hpp
./CordicFunctionGen 31 > ../src/fixed_cordic/cordic-31b.hpp > ../src/fixed_cordic/cordic-31b.hpp
